version: '3'

services:

  opencart:
    image: vimagick/opencart
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - /var/www/html
    env_file:
      - .env

  mysql:
    image: mysql
    env_file:
      - .env
